project:
  type: book

book:
  title: "R Graphics Cookbook, 2nd edition"
  author: "Winston Chang"
  cover-image: cover.jpg
  repo-url: https://github.com/bryanlockwald/rgcookbook
  chapters:
    - index.qmd
    - ch00.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd
    - ch04.qmd
    - ch05.qmd
    - ch06.qmd
    - ch07.qmd
    - ch08.qmd
    - ch09.qmd
    - ch10.qmd
    - ch11.qmd
    - ch12.qmd
    - ch13.qmd
    - ch14.qmd
    - ch15.qmd
  appendices:
    - ggplot-appendix.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  eval: true
  echo: true
  warning: false
  cache: true

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
    fig.align: "center"
    fig.width: 5
    fig.height: 4
